import type { NextPage } from 'next';
import Head from 'next/head';
import DistributerTableHead from '../../src/components/DistributerTableHead';
import DistributerTableItem from '../../src/components/DistributerTableItem';

const Distributers: NextPage = () => {
  const demoItem = [
    { name: '1' },
    { name: '2' },
    { name: '3' },
    { name: '4' },
    { name: '5' },
    { name: '6' },
    { name: '7' },
    { name: '8' },
    { name: '9' },
    { name: '10' },
  ];
  return (
    <div className="page-wrapper">
      <Head>
        <title>Jolly Classroom | Distributers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="invoices-page">
        <div className="w-full max-w-siteContainer mx-auto px-4">
          <div className="page-head flex justify-between items-center py-6">
            <div className="title">
              <h1 className="text-2xl text-DarkGray font-bold Quicksand">
                Distributers
              </h1>
            </div>
            <div className="right">
              <div className="distributer-search relative w-[312px]">
                <input
                  type="text"
                  placeholder="Search distributer"
                  className="w-full h-12 text-MidGray border border-solid border-MidGray rounded-full pl-12 pr-2 outline-none bg-transparent"
                />
                <button type="submit" className="absolute top-[14px] left-4">
                  <svg
                    width="20"
                    height="20"
                    viewBox="0 0 20 20"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fillRule="evenodd"
                      clipRule="evenodd"
                      d="M0 7.5C0 11.642 3.358 15 7.5 15C9.232 15 10.826 14.413 12.096 13.427C12.143 13.529 12.209 13.623 12.293 13.707L18.293 19.707C18.683 20.098 19.317 20.098 19.707 19.707C20.098 19.317 20.098 18.683 19.707 18.293L13.707 12.293C13.623 12.209 13.529 12.143 13.427 12.096C14.413 10.826 15 9.232 15 7.5C15 3.358 11.642 0 7.5 0C3.358 0 0 3.358 0 7.5ZM2 7.5C2 4.462 4.462 2 7.5 2C10.538 2 13 4.462 13 7.5C13 10.538 10.538 13 7.5 13C4.462 13 2 10.538 2 7.5Z"
                      fill="#9A9FB8"
                    />
                  </svg>
                </button>
              </div>
            </div>
          </div>

          <div className="table bg-white w-full rounded-lg">
            <DistributerTableHead />
            {demoItem.map((details, index) => (
              <DistributerTableItem key={index} />
            ))}
          </div>
          <div className="add-distributer mt-4">
            <button
              type="button"
              className="text-BrandBlue text-base Quicksand flex items-center ml-auto mr-0"
            >
              Add new distributer{' '}
              <svg
                width="20"
                height="20"
                viewBox="0 0 20 20"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                className="ml-2"
              >
                <path
                  fillRule="evenodd"
                  clipRule="evenodd"
                  d="M10 20C4.477 20 0 15.523 0 10C0 4.477 4.477 0 10 0C15.523 0 20 4.477 20 10C20 15.523 15.523 20 10 20ZM10 2C5.582 2 2 5.582 2 10C2 14.418 5.582 18 10 18C14.418 18 18 14.418 18 10C18 5.582 14.418 2 10 2ZM10 4.757C10.553 4.757 11 5.205 11 5.757V9H14.243C14.795 9 15.243 9.448 15.243 10C15.243 10.552 14.795 11 14.243 11H11V14.243C11 14.795 10.553 15.243 10 15.243C9.448 15.243 9 14.795 9 14.243V11H5.757C5.205 11 4.757 10.552 4.757 10C4.757 9.448 5.205 9 5.757 9H9V5.757C9 5.205 9.448 4.757 10 4.757Z"
                  fill="#4A6FFF"
                />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Distributers;
