import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const singleInvoiceCodes: NextPage = () => {
  return (
    <div className="page-wrapper">
      <Head>
        <title>Jolly Classroom | 035-2022-07 codes sold</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="invoices-page">
        <div className="w-full max-w-siteContainer mx-auto px-4">
          <div className="page-nav flex items-center py-3">
            <Link href="/invoices">
              <a className="text-base text-BrandBlue">Invoices</a>
            </Link>
            <svg
              width="8"
              height="14"
              viewBox="0 0 8 14"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
              className="mx-4"
            >
              <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M0.29325 0.29325C0.68325 -0.09775 1.31725 -0.09775 1.70725 0.29325L7.70725 6.29325C8.09825 6.68325 8.09825 7.31725 7.70725 7.70725L1.70725 13.7072C1.31725 14.0982 0.68325 14.0982 0.29325 13.7072C-0.09775 13.3172 -0.09775 12.6833 0.29325 12.2933L5.58625 7.00025L0.29325 1.70725C-0.09775 1.31725 -0.09775 0.68325 0.29325 0.29325Z"
                fill="#9A9FB8"
                fillOpacity="0.32"
              />
            </svg>
            <span className="text-base text-PrimaryGray">
              035-2022-07 codes sold
            </span>
          </div>

          <div className="page-head flex justify-between items-center pt-4">
            <div className="title">
              <h1 className="text-2xl text-DarkGray font-bold Quicksand">
                035-2022-07 codes sold
              </h1>
            </div>
          </div>

          <div className="single-invoice-content">
            <div className="details">
              <p className=" text-base text-DarkGray py-2">
                <strong className="Quicksand">Distributer: </strong>Booksshop (
                <a href="mailto:bookshop@gmail.com" className="text-BrandBlue">
                  bookshop@gmail.com
                </a>
                )
              </p>
              <p className=" text-base text-DarkGray py-2">
                <strong className="Quicksand">Period: </strong>Q2 2022
              </p>
              <p className=" text-base text-DarkGray py-2">
                <strong className="Quicksand">Invoice: </strong>
                <a href="tel:+34 986 748 834" className="text-BrandBlue">
                  035-2022-07
                </a>
              </p>
            </div>
          </div>

          <div className="invoice-single-codes-table mt-10 bg-white rounded-head overflow-hidden">
            <div className="table-head flex items-center bg-SoftGray px-12 py-4 overflow-hidden rounded-head">
              <div className="code w-[20%] text-base text-DarkGray font-bold Quicksand text-left">
                Code
              </div>
              <div className="subscription w-[26.66%] text-base text-DarkGray font-bold Quicksand text-right">
                Subscription duration
              </div>
              <div className="redeem w-[26.66%] text-base text-DarkGray font-bold Quicksand">
                <div className="inner max-w-[160px] ml-auto mr-0 text-left">
                  Redeem date
                </div>
              </div>
              <div className="total w-[26.66%] text-base text-DarkGray font-bold Quicksand">
                <div className="inner max-w-[160px] ml-auto mr-0 text-left">
                  Customer
                </div>
              </div>
            </div>

            <div className="table-item flex items-center px-12 py-4 transition ease-in hover:bg-SoftGray/40 border-t border-solid border-SoftGray">
              <div className="code w-[20%] text-base text-PrimaryGray text-left">
                8dj29dj20e
              </div>
              <div className="cost w-[26.66%] text-base text-PrimaryGray text-right">
                1 year (100.00€)
              </div>
              <div className="amount w-[26.66%] text-base text-PrimaryGray text-right">
                <div className="inner max-w-[160px] ml-auto mr-0 text-left">
                  11/02/2022
                </div>
              </div>
              <div className="total w-[26.66%] text-base text-PrimaryGray text-right">
                <div className="inner max-w-[160px] ml-auto mr-0 text-left">
                  <a href="mailto:user@gmail.com">user@gmail.com</a>
                </div>
              </div>
            </div>
            <div className="table-item flex items-center px-12 py-4 transition ease-in hover:bg-SoftGray/40 border-t border-solid border-SoftGray">
              <div className="code w-[20%] text-base text-PrimaryGray text-left">
                8dj29dj20e
              </div>
              <div className="cost w-[26.66%] text-base text-PrimaryGray text-right">
                1 year (100.00€)
              </div>
              <div className="amount w-[26.66%] text-base text-PrimaryGray text-right">
                <div className="inner max-w-[160px] ml-auto mr-0 text-left">
                  11/02/2022
                </div>
              </div>
              <div className="total w-[26.66%] text-base text-PrimaryGray text-right">
                <div className="inner max-w-[160px] ml-auto mr-0 text-left">
                  <a href="mailto:user@gmail.com">user@gmail.com</a>
                </div>
              </div>
            </div>
            <div className="table-item flex items-center px-12 py-4 transition ease-in hover:bg-SoftGray/40 border-t border-solid border-SoftGray">
              <div className="code w-[20%] text-base text-PrimaryGray text-left">
                8dj29dj20e
              </div>
              <div className="cost w-[26.66%] text-base text-PrimaryGray text-right">
                1 year (100.00€)
              </div>
              <div className="amount w-[26.66%] text-base text-PrimaryGray text-right">
                <div className="inner max-w-[160px] ml-auto mr-0 text-left">
                  11/02/2022
                </div>
              </div>
              <div className="total w-[26.66%] text-base text-PrimaryGray text-right">
                <div className="inner max-w-[160px] ml-auto mr-0 text-left">
                  <a href="mailto:user@gmail.com">user@gmail.com</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default singleInvoiceCodes;
