import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const singleInvoice: NextPage = () => {
  return (
    <div className="page-wrapper">
      <Head>
        <title>Jolly Classroom | Invoice 035-2022-07</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="invoices-page">
        <div className="w-full max-w-siteContainer mx-auto px-4">
          <div className="page-nav flex items-center py-3">
            <Link href="/invoices">
              <a className="text-base text-BrandBlue">Invoices</a>
            </Link>
            <svg
              width="8"
              height="14"
              viewBox="0 0 8 14"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
              className="mx-4"
            >
              <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M0.29325 0.29325C0.68325 -0.09775 1.31725 -0.09775 1.70725 0.29325L7.70725 6.29325C8.09825 6.68325 8.09825 7.31725 7.70725 7.70725L1.70725 13.7072C1.31725 14.0982 0.68325 14.0982 0.29325 13.7072C-0.09775 13.3172 -0.09775 12.6833 0.29325 12.2933L5.58625 7.00025L0.29325 1.70725C-0.09775 1.31725 -0.09775 0.68325 0.29325 0.29325Z"
                fill="#9A9FB8"
                fillOpacity="0.32"
              />
            </svg>
            <span className="text-base text-PrimaryGray">
              Invoice 035-2022-07
            </span>
          </div>

          <div className="page-head flex justify-between items-center py-4">
            <div className="title">
              <h1 className="text-2xl text-DarkGray font-bold Quicksand">
                Invoice 035-2022-07
              </h1>
            </div>
            <div className="right">
              <button
                type="button"
                className="text-base text-white Quicksand font-bold bg-BrandBlue rounded-3xl py-3 px-6 transition ease-in hover:bg-BrandBlueDark"
              >
                Send
              </button>
            </div>
          </div>

          <div className="single-invoice-content">
            <div className="date flex items-center pt-4">
              <p className="text-base text-DarkGray mr-7">
                <strong className="Quicksand">Date: </strong>01/07/2021
              </p>
              <p className="text-base text-DarkGray">
                <strong className="Quicksand">Invoice nº: </strong>035
              </p>
            </div>

            <div className="sender-receiver flex flex-wrap pt-10">
              <div className="from w-2/6">
                <p className="title text-xs uppercase w-[50px] h-7 bg-SoftGray rounded-lg flex items-center justify-center mb-4">
                  From
                </p>
                <h2 className="Quicksand text-DarkGray font-bold text-base pb-2">
                  Jolly Learning
                </h2>
                <p className=" text-base text-DarkGray py-2">
                  <strong className="Quicksand">User name: </strong>Jonh Doe
                </p>
                <p className=" text-base text-DarkGray py-2">
                  <strong className="Quicksand">Email: </strong>
                  <a href="mailto:jonh@bookshop.com">jonh@bookshop.com</a>
                </p>
                <p className=" text-base text-DarkGray py-2">
                  <strong className="Quicksand">Phone: </strong>
                  <a href="tel:+34 986 748 834">+34 986 748 834</a>
                </p>
              </div>
              <div className="to w-2/6">
                <p className="title text-xs uppercase w-[33px] h-7 bg-SoftGray rounded-lg flex items-center justify-center mb-4">
                  to
                </p>
                <h2 className="Quicksand text-DarkGray font-bold text-base pb-2">
                  Bookshop
                </h2>
                <p className="text-base text-DarkGray py-2">
                  <strong className="Quicksand">User name: </strong>Jonh Doe
                </p>
                <p className="text-base text-DarkGray py-2">
                  <strong className="Quicksand">Email: </strong>
                  <a href="mailto:jonh@bookshop.com">jonh@bookshop.com</a>
                </p>
                <p className="text-base text-DarkGray py-2">
                  <strong className="Quicksand">Phone: </strong>
                  <a href="tel:+34 986 748 834">+34 986 748 834</a>
                </p>
              </div>
            </div>
          </div>

          <div className="invoice-single-table mt-10 bg-white">
            <div className="table-head flex items-center bg-SoftGray px-12 py-4 overflow-hidden rounded-head">
              <div className="code w-[26.66%] text-base text-DarkGray font-bold Quicksand text-left">
                Code
              </div>
              <div className="cost w-[20%] text-base text-DarkGray font-bold Quicksand text-right">
                Cost
              </div>
              <div className="amount w-[26.66%] text-base text-DarkGray font-bold Quicksand text-right">
                Amount
              </div>
              <div className="total w-[26.66%] text-base text-DarkGray font-bold Quicksand text-right">
                Total
              </div>
            </div>

            <div className="table-item flex items-center px-12 py-4 transition ease-in hover:bg-SoftGray/40">
              <div className="code w-[26.66%] text-base text-PrimaryGray text-left">
                1 yesr subscription
              </div>
              <div className="cost w-[20%] text-base text-PrimaryGray text-right">
                100.00€
              </div>
              <div className="amount w-[26.66%] text-base text-PrimaryGray text-right">
                3
              </div>
              <div className="total w-[26.66%] text-base text-PrimaryGray text-right">
                300.00€
              </div>
            </div>
            <div className="table-item flex items-center px-12 py-4 transition ease-in hover:bg-SoftGray/40">
              <div className="code w-[26.66%] text-base text-PrimaryGray text-left">
                1 yesr subscription
              </div>
              <div className="cost w-[20%] text-base text-PrimaryGray text-right">
                100.00€
              </div>
              <div className="amount w-[26.66%] text-base text-PrimaryGray text-right">
                3
              </div>
              <div className="total w-[26.66%] text-base text-PrimaryGray text-right">
                300.00€
              </div>
            </div>
            <div className="table-item flex items-center px-12 py-4 transition ease-in hover:bg-SoftGray/40">
              <div className="code w-[26.66%] text-base text-PrimaryGray text-left">
                1 yesr subscription
              </div>
              <div className="cost w-[20%] text-base text-PrimaryGray text-right">
                100.00€
              </div>
              <div className="amount w-[26.66%] text-base text-PrimaryGray text-right">
                3
              </div>
              <div className="total w-[26.66%] text-base text-PrimaryGray text-right">
                300.00€
              </div>
            </div>
          </div>

          <div className="total-count w-full max-w-[235px] ml-auto mr-0 pt-8">
            <p className="text-base text-DarkGray py-2">
              <strong className="Quicksand w-32 inline-block">Subtotal </strong>
              700.00€
            </p>
            <p className="text-base text-DarkGray py-2">
              <strong className="Quicksand w-32 inline-block">Taxes </strong>
            </p>
            <p className="text-base text-DarkGray py-2">
              <strong className="Quicksand w-32 inline-block">Total </strong>
              700.00€
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default singleInvoice;
