import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import CustomerTableHead from '../../src/components/CustomerTableHead';
import CustomerTableItem from '../../src/components/CustomerTableItem';

const Customers: NextPage = () => {
  const demoItem = [
    { name: '1' },
    { name: '2' },
    { name: '3' },
    { name: '4' },
    { name: '5' },
    { name: '6' },
    { name: '7' },
    { name: '8' },
    { name: '9' },
    { name: '10' },
  ];
  return (
    <div className="page-wrapper">
      <Head>
        <title>Jolly Classroom | Customers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="invoices-page">
        <div className="w-full max-w-siteContainer mx-auto">
          <div className="page-nav flex items-center py-3">
            <Link href="/">
              <a className="text-base text-BrandBlue">Home</a>
            </Link>
            <svg
              width="8"
              height="14"
              viewBox="0 0 8 14"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
              className="mx-4"
            >
              <path
                fillRule="evenodd"
                clipRule="evenodd"
                d="M0.29325 0.29325C0.68325 -0.09775 1.31725 -0.09775 1.70725 0.29325L7.70725 6.29325C8.09825 6.68325 8.09825 7.31725 7.70725 7.70725L1.70725 13.7072C1.31725 14.0982 0.68325 14.0982 0.29325 13.7072C-0.09775 13.3172 -0.09775 12.6833 0.29325 12.2933L5.58625 7.00025L0.29325 1.70725C-0.09775 1.31725 -0.09775 0.68325 0.29325 0.29325Z"
                fill="#9A9FB8"
                fillOpacity="0.32"
              />
            </svg>
            <span className="text-base text-PrimaryGray">Customers</span>
          </div>
          <div className="page-head flex justify-between items-center py-6">
            <div className="title">
              <h1 className="text-2xl text-DarkGray font-bold Quicksand">
                Customers
              </h1>
            </div>
          </div>

          <div className="table bg-white w-full rounded-lg">
            <CustomerTableHead />
            {demoItem.map((details, index) => (
              <CustomerTableItem key={index} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Customers;
