import type { NextPage } from 'next';
import Head from 'next/head';

const Invoices: NextPage = () => {
  return (
    <div className="page-container">
      <Head>
        <title>Jolly Classroom | Invoices</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="invoices-page"></div>
    </div>
  );
};

export default Invoices;
