import type { NextPage } from 'next';
import Head from 'next/head';
import CreateCodesForm from '../../src/components/codes/CreateCodesForm';
import Instructions from '../../src/components/codes/Instructions';

const Codes: NextPage = () => {
  return (
    <div className="page-wrapper">
      <Head>
        <title>Codes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="page page-codes">
        <Instructions />
        <CreateCodesForm />
      </div>
    </div>
  );
};

export default Codes;
